package saudecap;

/**
 *
 * @author wsilva
 */
public class Cartela extends javax.swing.JDialog {

    /**
     * Creates new form Cartela
     *
     * @param parent
     * @param modal
     * @param numero
     */
    public Cartela(java.awt.Frame parent, boolean modal, int numero) {
        super(parent, modal);
        initComponents();
        this.setTitle("Cartela No. " + numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCartelas = new javax.swing.JPanel();
        sorteio1 = new javax.swing.JPanel();
        sorteio1_C1 = new saudecap.CartelaUnica();
        sorteio1_C2 = new saudecap.CartelaUnica();
        sorteio2 = new javax.swing.JPanel();
        sorteio2_C1 = new saudecap.CartelaUnica();
        sorteio2_C2 = new saudecap.CartelaUnica();
        sorteio3 = new javax.swing.JPanel();
        sorteio3_C1 = new saudecap.CartelaUnica();
        sorteio3_C2 = new saudecap.CartelaUnica();
        sorteio4 = new javax.swing.JPanel();
        sorteio4_C1 = new saudecap.CartelaUnica();
        sorteio4_C2 = new saudecap.CartelaUnica();
        chkSorteio1 = new javax.swing.JCheckBox();
        chkSorteio2 = new javax.swing.JCheckBox();
        chkSorteio3 = new javax.swing.JCheckBox();
        chkSorteio4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sorteio1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorteio 1"));

        javax.swing.GroupLayout sorteio1Layout = new javax.swing.GroupLayout(sorteio1);
        sorteio1.setLayout(sorteio1Layout);
        sorteio1Layout.setHorizontalGroup(
            sorteio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sorteio1_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sorteio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sorteio1_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sorteio1Layout.setVerticalGroup(
            sorteio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio1Layout.createSequentialGroup()
                .addComponent(sorteio1_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteio1_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sorteio2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorteio 2"));

        javax.swing.GroupLayout sorteio2Layout = new javax.swing.GroupLayout(sorteio2);
        sorteio2.setLayout(sorteio2Layout);
        sorteio2Layout.setHorizontalGroup(
            sorteio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio2Layout.createSequentialGroup()
                .addGroup(sorteio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sorteio2_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio2_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        sorteio2Layout.setVerticalGroup(
            sorteio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio2Layout.createSequentialGroup()
                .addComponent(sorteio2_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteio2_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        sorteio3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorteio 3"));

        javax.swing.GroupLayout sorteio3Layout = new javax.swing.GroupLayout(sorteio3);
        sorteio3.setLayout(sorteio3Layout);
        sorteio3Layout.setHorizontalGroup(
            sorteio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio3Layout.createSequentialGroup()
                .addGroup(sorteio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sorteio3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        sorteio3Layout.setVerticalGroup(
            sorteio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio3Layout.createSequentialGroup()
                .addComponent(sorteio3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteio3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        sorteio4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorteio 4"));

        javax.swing.GroupLayout sorteio4Layout = new javax.swing.GroupLayout(sorteio4);
        sorteio4.setLayout(sorteio4Layout);
        sorteio4Layout.setHorizontalGroup(
            sorteio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sorteio4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sorteio4_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(sorteio4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sorteio4_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sorteio4Layout.setVerticalGroup(
            sorteio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteio4Layout.createSequentialGroup()
                .addComponent(sorteio4_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sorteio4_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chkSorteio1.setSelected(true);
        chkSorteio1.setText("Sorteio 1");
        chkSorteio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSorteio1ActionPerformed(evt);
            }
        });

        chkSorteio2.setSelected(true);
        chkSorteio2.setText("Sorteio 2");
        chkSorteio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSorteio2ActionPerformed(evt);
            }
        });

        chkSorteio3.setSelected(true);
        chkSorteio3.setText("Sorteio 3");
        chkSorteio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSorteio3ActionPerformed(evt);
            }
        });

        chkSorteio4.setSelected(true);
        chkSorteio4.setText("Sorteio 4");
        chkSorteio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSorteio4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCartelasLayout = new javax.swing.GroupLayout(pnlCartelas);
        pnlCartelas.setLayout(pnlCartelasLayout);
        pnlCartelasLayout.setHorizontalGroup(
            pnlCartelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartelasLayout.createSequentialGroup()
                .addGroup(pnlCartelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartelasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(chkSorteio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkSorteio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSorteio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkSorteio4))
                    .addGroup(pnlCartelasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sorteio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sorteio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sorteio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sorteio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlCartelasLayout.setVerticalGroup(
            pnlCartelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartelasLayout.createSequentialGroup()
                .addGroup(pnlCartelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSorteio1)
                    .addComponent(chkSorteio2)
                    .addComponent(chkSorteio3)
                    .addComponent(chkSorteio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCartelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sorteio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCartelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCartelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSorteio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSorteio1ActionPerformed
        sorteio1.setVisible(chkSorteio1.isSelected());
    }//GEN-LAST:event_chkSorteio1ActionPerformed

    private void chkSorteio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSorteio2ActionPerformed
        sorteio2.setVisible(chkSorteio2.isSelected());
    }//GEN-LAST:event_chkSorteio2ActionPerformed

    private void chkSorteio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSorteio3ActionPerformed
        sorteio3.setVisible(chkSorteio3.isSelected());
    }//GEN-LAST:event_chkSorteio3ActionPerformed

    private void chkSorteio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSorteio4ActionPerformed
        sorteio4.setVisible(chkSorteio4.isSelected());
    }//GEN-LAST:event_chkSorteio4ActionPerformed

    public void busca(int numero, boolean b) {
        if (chkSorteio1.isSelected()) {
            sorteio1_C1.verifica(numero, b);
            sorteio1_C2.verifica(numero, b);
        }

        if (chkSorteio2.isSelected()) {
            sorteio2_C1.verifica(numero, b);
            sorteio2_C2.verifica(numero, b);
        }

        if (chkSorteio3.isSelected()) {
            sorteio3_C1.verifica(numero, b);
            sorteio3_C2.verifica(numero, b);
        }

        if (chkSorteio4.isSelected()) {
            sorteio4_C1.verifica(numero, b);
            sorteio4_C2.verifica(numero, b);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSorteio1;
    private javax.swing.JCheckBox chkSorteio2;
    private javax.swing.JCheckBox chkSorteio3;
    private javax.swing.JCheckBox chkSorteio4;
    private javax.swing.JPanel pnlCartelas;
    private javax.swing.JPanel sorteio1;
    private saudecap.CartelaUnica sorteio1_C1;
    private saudecap.CartelaUnica sorteio1_C2;
    private javax.swing.JPanel sorteio2;
    private saudecap.CartelaUnica sorteio2_C1;
    private saudecap.CartelaUnica sorteio2_C2;
    private javax.swing.JPanel sorteio3;
    private saudecap.CartelaUnica sorteio3_C1;
    private saudecap.CartelaUnica sorteio3_C2;
    private javax.swing.JPanel sorteio4;
    private saudecap.CartelaUnica sorteio4_C1;
    private saudecap.CartelaUnica sorteio4_C2;
    // End of variables declaration//GEN-END:variables
}
